site:
  title: Jenkins Docs
  start_page: user-docs::index.adoc

content:
  sources:
    - url: ../
      # remember well to change the branch name to the one you are working on to generate the preview
      branches: [fix/patch-issues-with-advisories-setup]
      start_paths: [docs/tutorials, docs/user-docs, docs/solutions]
      # developer docs are un-versioned that's why they are to be fetched individually
    - url: ../
      # remember well to change the branch name to the one you are working on to generate the preview
      branches: [fix/patch-issues-with-advisories-setup]
      start_paths: [docs/dev-docs, docs/events, docs/security, docs/sigs, docs/projects, docs/images, docs/books, docs/community, docs/project, docs/about, docs/download]

runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    level: error

asciidoc:
  attributes:
    page-pagination: ''
    plugin: https://plugins.jenkins.io/
    jira: https://issues.jenkins.io/browse/
    jep: https://github.com/jenkinsci/jep/tree/master/jep/
    matrix: https://matrix.to/#/#
    email: jenkinsci-users@googlegroups.com
    
ui:
  bundle:
    url: ../ui/build/ui-bundle.zip
    snapshot: true
