---
layout: pipelinesteps
title: "Cyber Chief Security Scanner"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Cyber Chief Security Scanner

plugin:cyberchief-security-scanner[View this plugin on the Plugins site]

=== `greet`: Cyber Chief Security Scanner
++++
<ul><li><code>authToken</code> (optional)
<div><div>
 Cyber Chief Auth Token.
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>apiUrl : String</code> (optional)
<div><div>
 Cyber Chief Automated Test Endpoint.
</div></div>

</li>
<li><code>apiName : String</code> (optional)
<div><div>
 Your API Name set in Workspace Admin in Cyber Chief.
</div></div>

</li>
<li><code>raiderName : String</code> (optional)
</li>
<li><code>regions : Array / List of String</code> (optional)
<div><div>
 Select Select for the Raider Scanner to run.
</div></div>

<ul></ul></li>
<li><code>frameworks : Array / List of String</code> (optional)
<div><div>
 Select Framework for Raider Scanner.
</div></div>

<ul></ul></li>
<li><code>services : Array / List of String</code> (optional)
<div><div>
 Select AWS Services for the Raider Scanner.
</div></div>

<ul></ul></li>
<li><code>scanType : String</code> (optional)
<div><div>
 Cyber Chief Scan Type. Choose either of these: <i> Web App Scan, Bolt API Security, Raider CPSM </i>
</div></div>

</li>
<li><code>testScope : String</code> (optional)
<div><div>
 Cyber Chief Test Scope. Choose either of these: <i> reconnaissance, attack, infiltration </i>
</div></div>

</li>
<li><code>failOnHighVulns : boolean</code> (optional)
</li>
<li><code>failOnHighMediumVulns : boolean</code> (optional)
</li>
</ul>


++++
