---
layout: pipelinesteps
title: "Machine Learning Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Machine Learning Plugin

plugin:machine-learning[View this plugin on the Plugins site]

=== `ipythonBuilder`: IPython Builder
++++
<ul><li><code>code : String</code>
<div><div>
 Copy and paste your code to execute in selected server 
 <p>Eg: print(" Hello Jenkins, from Machine Learning Plugin ...... ! ")</p>
</div></div>

</li>
<li><code>filePath : String</code>
<div><div>
 Path of file that contains python code to be executed in the server 
 <p>Eg: /home/alice/iris/ml.py</p>
</div></div>

</li>
<li><code>parserType : String</code>
</li>
<li><code>task : String</code>
<div><div>
 Folder name that will be used for saving html/images/graphs generated by the script file or code 
 <p>Eg: Training</p>
</div></div>

</li>
<li><code>kernelName : String</code>
<div><div>
 Globally configured Jupyter kernels. If any kernels are not shown 
 <ul>
  <li>Manage Jenkins --&gt; Configure System</li>
  <li>Under Kernel Configuration</li>
  <ul>
   <li>Add a name for kernel (Required)</li>
   <li>Language (Optional)</li>
   <li>Add timeout for launching</li>
   <li>Add max size of results that can be obtained form the kernel</li>
  </ul>
 </ul>
</div></div>

</li>
</ul>


++++
