---
layout: pipelinesteps
title: "Redeploy Rancher2.x Workload Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Redeploy Rancher2.x Workload Plugin

plugin:redeploy-rancher2-workload[View this plugin on the Plugins site]

=== `rancherRedeploy`: Redeploy Rancher2.x Workload
++++
<ul><li><code>credential : String</code>
</li>
<li><code>workload : String</code>
<div><div>
 you can find your workload API path in Rancher2.x web UI--&gt;Cluster-&gt;Project-&gt;Resources-&gt;Workloads, 
 <br>
  copy the workload link address, eg: http://localhost/p/c-h4hxd:p-dwqfr/workload/deployment:jenkins:jenkins 
 <br>
  or click the menu icon and select "View in API", will open in new browser tab. copy that url to here. 
 <br>
 <p>since endpoint part has bean set in Credential, you only need specify path from "/p/" or "/project", eg: <br><b>/project/c-h4hxd:p-c9j8z/workloads/deployment:default:busybox </b><br>
   or <b>/p/c-h4hxd:p-dwqfr/workload/deployment:jenkins:jenkins </b></p>
</div></div>

</li>
<li><code>images : String</code>
<div><div>
 update image version to your excepted. optional if you use latest as image version or imagePullPolicy="Always"
 <br>
  you can use semicolon(;) to split multiple images, eg: 
 <p>nginx;nginx:1.0;myteam/myproject:v2.0;docker.io/team/image:v1.0.${BUILD_NUMBER}</p> this plugin will update all images in this workload by <b>match the name part exactly</b>, and simply set version part as you specified. so you may need Jenkins variables to dynamic generate new version number. 
 <br>
</div></div>

</li>
<li><code>alwaysPull : boolean</code>
<div><div>
 set imagePullPolicy to "Always"
</div></div>

</li>
</ul>


++++
