---
layout: pipelinesteps
title: "Redmine Metrics Report"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Redmine Metrics Report

plugin:redmine-metrics-report[View this plugin on the Plugins site]

=== `redmineMetricsReport`: Generate Redmine Metrics Report
++++
<ul><li><code>settings</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>url : String</code>
</li>
<li><code>apiKey : String</code>
<div><div>
 <p>Specify Redmine API Key which can be found in Redmine's [My Account] -&gt; API access key</p>
 <p>If can't find "API access key", Redmine admin needs to enable a setting. "Administration &gt; Settings &gt; Authentication &gt; Enable REST web service".</p>
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 <p>Specify Redmine Project's Identifier which you want to generate report for, use Identifier not Name in the Redmine project setting page.</p>
</div></div>

</li>
<li><code>customQueryId : int</code>
</li>
<li><code>sprintSize : int</code>
<div><div>
 <p>Specify the time span(day). e.g.: if you want to generate report on a weekly basis you should specify 7.</p>
</div></div>

</li>
</ul></li>
</ul>


++++
