---
layout: pipelinesteps
title: "Azure Service Fabric Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Azure Service Fabric Plugin

plugin:service-fabric[View this plugin on the Plugins site]

=== `azureServiceFabricPublish`: Deploy Service Fabric Project
++++
<ul><li><code>applicationName : String</code> (optional)
<div><div>
 The whole name of the application, which should be the name of the folder containing the ApplicationManifest with "fabric:/" added at the beginning.
</div></div>

</li>
<li><code>applicationType : String</code> (optional)
<div><div>
 Should match the specified ApplicationTypeName in the Application Manifest.
</div></div>

</li>
<li><code>azureCredentialsId : String</code> (optional)
</li>
<li><code>clientCert : String</code> (optional)
</li>
<li><code>clientKey : String</code> (optional)
</li>
<li><code>configureType : String</code> (optional)
</li>
<li><code>managementHost : String</code> (optional)
</li>
<li><code>manifestPath : String</code> (optional)
<div><div>
 The path from the home of your Github project to the folder containing the Application Manifest. For example, "MySFApp/MySFApp/ApplicationManifest.xml". Used to determine version number in the deployment process.
</div></div>

</li>
<li><code>resourceGroup : String</code> (optional)
</li>
<li><code>serviceFabric : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'ServiceFabricPublisher'])`: Deploy Service Fabric Project
++++
<ul><li><code>publishStep</code>
<ul><b>Nested Object</b>
<li><code>applicationName : String</code> (optional)
<div><div>
 The whole name of the application, which should be the name of the folder containing the ApplicationManifest with "fabric:/" added at the beginning.
</div></div>

</li>
<li><code>applicationType : String</code> (optional)
<div><div>
 Should match the specified ApplicationTypeName in the Application Manifest.
</div></div>

</li>
<li><code>azureCredentialsId : String</code> (optional)
</li>
<li><code>clientCert : String</code> (optional)
</li>
<li><code>clientKey : String</code> (optional)
</li>
<li><code>configureType : String</code> (optional)
</li>
<li><code>managementHost : String</code> (optional)
</li>
<li><code>manifestPath : String</code> (optional)
<div><div>
 The path from the home of your Github project to the folder containing the Application Manifest. For example, "MySFApp/MySFApp/ApplicationManifest.xml". Used to determine version number in the deployment process.
</div></div>

</li>
<li><code>resourceGroup : String</code> (optional)
</li>
<li><code>serviceFabric : String</code> (optional)
</li>
</ul></li>
</ul>


++++
