---
layout: pipelinesteps
title: "Progress TestStudio for API Plugin"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== Progress TestStudio for API Plugin

plugin:teststudioapitesting[View this plugin on the Plugins site]

=== `step([$class: 'TestStudioAPITestBuilder'])`: Test Studio for API runner configuration
++++
<div><div>
 Jenkins plugin for execution of Progress Test Studio for API tests.
</div></div>
<ul><li><code>apiRunnerPath : String</code> (optional)
<div><div>
 Full path to Test Studio for API Runner executable.
</div></div>

</li>
<li><code>project : String</code> (optional)
<div><div>
 The path to the project folder.
</div></div>

</li>
<li><code>test : String</code> (optional)
<div><div>
 Specify test/tests to run, one per line.
</div>
<br>
<div>
 Example: 
 <br>
  .\CRUD Tests\Get All Users
 <br>
  .\Get User Id By Its Username
 <br>
 <br>
</div></div>

</li>
<li><code>startFrom : String</code> (optional)
</li>
<li><code>stopAfter : String</code> (optional)
</li>
<li><code>variable : String</code> (optional)
<div><div>
 Specify test parameters in key=value pairs, one pair per line.
</div>
<br>
<div>
 Example: 
 <br>
  url=http://localhost:5000 
 <br>
  user-name="John Smith" 
 <br>
 <br>
</div></div>

</li>
<li><code>dontSaveContexts : boolean</code> (optional)
</li>
<li><code>testAsUnit : boolean</code> (optional)
<div><div>
 If checked Test Studio for API test will be converted to JUnit test, else test will be converted to testsuite and test steps will be converted to JUnit test.
</div></div>

</li>
</ul>


++++
