---
layout: pipelinesteps
title: "VectorCAST Coverage"
---

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:

== VectorCAST Coverage

plugin:vectorcast-coverage[View this plugin on the Plugins site]

=== `step([$class: 'VectorCASTPublisher'])`: Record VectorCAST Coverage Information
++++
<ul><li><code>maxHistory : int</code>
</li>
<li><code>includes : String</code> (optional)
</li>
<li><code>useThreshold : boolean</code> (optional)
</li>
<li><code>healthyTarget</code> (optional)
<ul><b>Nested Object</b>
<li><code>minStatement : int</code>
</li>
<li><code>maxStatement : int</code>
</li>
<li><code>minBranch : int</code>
</li>
<li><code>maxBranch : int</code>
</li>
<li><code>minBasisPath : int</code>
</li>
<li><code>maxBasisPath : int</code>
</li>
<li><code>minMCDC : int</code>
</li>
<li><code>maxMCDC : int</code>
</li>
<li><code>minFunction : int</code>
</li>
<li><code>maxFunction : int</code>
</li>
<li><code>minFunctionCall : int</code>
</li>
<li><code>maxFunctionCall : int</code>
</li>
</ul></li>
<li><code>unhealthyTarget</code> (optional)
<ul><b>Nested Object</b>
<li><code>minStatement : int</code>
</li>
<li><code>maxStatement : int</code>
</li>
<li><code>minBranch : int</code>
</li>
<li><code>maxBranch : int</code>
</li>
<li><code>minBasisPath : int</code>
</li>
<li><code>maxBasisPath : int</code>
</li>
<li><code>minMCDC : int</code>
</li>
<li><code>maxMCDC : int</code>
</li>
<li><code>minFunction : int</code>
</li>
<li><code>maxFunction : int</code>
</li>
<li><code>minFunctionCall : int</code>
</li>
<li><code>maxFunctionCall : int</code>
</li>
</ul></li>
<li><code>useCoverageHistory : boolean</code> (optional)
</li>
<li><code>healthReports</code> (optional)
<ul><b>Nested Object</b>
<li><code>minStatement : int</code>
</li>
<li><code>maxStatement : int</code>
</li>
<li><code>minBranch : int</code>
</li>
<li><code>maxBranch : int</code>
</li>
<li><code>minBasisPath : int</code>
</li>
<li><code>maxBasisPath : int</code>
</li>
<li><code>minMCDC : int</code>
</li>
<li><code>maxMCDC : int</code>
</li>
<li><code>minFunction : int</code>
</li>
<li><code>maxFunction : int</code>
</li>
<li><code>minFunctionCall : int</code>
</li>
<li><code>maxFunctionCall : int</code>
</li>
</ul></li>
</ul>


++++
