= Jenkins Use-cases

[.card]
[.android]
== xref:android.adoc[Android]
[.data]
[.img]
image:images:ROOT:solution-images/android.svg[link=android.html]

[.card]
[.bit-bucket]
== xref:bitbucketserver.adoc[Bitbucket Server]
[.data]
[.img]
[#invert]
image:images:ROOT:solution-images/bitbucketserver.svg[link=bitbucketserver.html]

[.card]
[.c]
== xref:c.adoc[C/C++]
[.data]
[.img]
[#invert]
image:images:ROOT:solution-images/c.svg[link=c.html]

[.card]
[.docker]
== xref:docker.adoc[Docker]
[.data]
[.img]
image:images:ROOT:solution-images/docker.svg[link=docker.html]

[.card]
[.embedded-card]
// don't rename the above class or it will mess with table of content's embedded class on smaller screens.
== xref:embedded.adoc[Embedded]
[.data]
[.img]
image:images:ROOT:solution-images/embedded.svg[link=embedded.html]

[.card]
[.github]
== xref:github.adoc[Github]
[.data]
[.img]
[#invert]
image:images:ROOT:solution-images/github.svg[link=github.html]

[.card]
[.java]
== xref:java.adoc[Java]
[.data]
[.img]
image:images:ROOT:solution-images/java.svg[link=java.html]

[.card]
[.php]
== xref:php.adoc[PHP]
[.data]
[.img]
image:images:ROOT:solution-images/php.svg[link=php.html]

[.card]
[.pipeline]
== xref:pipeline.adoc[Continuous Delivery]
[.data]
[.img]
image:images:ROOT:solution-images/pipeline.svg[link=pipeline.html]

[.card]
[.python]
== xref:python.adoc[Python]
[.data]
[.img]
image:images:ROOT:solution-images/python.svg[link=python.html]

[.card]
[.ruby]
== xref:ruby.adoc[Ruby]
[.data]
[.img]
[#invert]
image:images:ROOT:solution-images/ruby.svg[link=ruby.html]

++++
<style>
.doc .img{
  margin:0;
}

/** hiding the anchor to the cards as it's not needed on this page */
.anchor{
  display: none;
}

.card {
  background-color: #fff;
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
  width: 155px;
  height:200px;
  display: inline-flex;
  align-items: center;
  justify-items: center;
  flex-direction: column;
  border-radius: 0.66rem;
  padding: 1rem;
}
.card a{
  color: rgba(0, 0, 0, 0.9);
}

.doc a:hover {
    color: white;
}

/** Grouping them will not apply the css*/
.github a{
  color:white;
}
.ruby a{
  color:white;
}
.c a{
  color:white;
}
.bit-bucket a{
  color:white;
}

.card h2{
  border: none !important;
  margin-top: 0;
  padding-top: 0;
  color: #1F2937;
  font-size: 1rem;
  font-weight: 700;
  text-align: center;
}

.card .data img{
    height: 96px;
    opacity: .55;
    margin: auto;
}

#invert{
  filter: invert(1);
}

#white{
  color: #fff;
}
.title span svg {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: #ffffff;
  height: 1rem;
}

.title-text {
  margin-left: 0.5rem;
  color: #374151;
  font-size: 18px;
}

.data {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
}

.data p {
  margin-top: 1rem;
  color: #1F2937;
  font-size: 1.5rem;
  line-height: 2.5rem;
  font-weight: 700;
  text-align: left;
  display: flex;
  justify-content: center;
}

.android{
    background-color: #3DDC84;
}

.php{
    background-color: #777BB4;
}

.docker{
    background-color: #2496ED;
}

.python{
    background-color: #4786BB;
}

.ruby{
    background-color: #C2322D;
    color: rgba(255, 255, 255, 0.9);
}

.pipeline{
    background-color: #FEAA2D;
}

.github{
    background-color: #181817;
    color: rgba(255, 255, 255, 0.9);
}

.embedded-card{
    background-color: #EE7272;
}

.bit-bucket{
  background-color: #0052CC;
  color: rgba(255, 255, 255, 0.9);
}

.c{
    background-color: #00599C;
    color: rgba(255, 255, 255, 0.9);
}

.java{
    background-color: #0093A6;
}
</style>


++++
