= Jenkins Events

There are many online and local Jenkins-related events: including conferences, meetups, webinars, hackathons, etc.

* xref:online-meetup:index.adoc[Jenkins Online Meetup]. Our project has a virtual meetup for users and developers. We organize regular events and webinars there.
* xref:projects:jam:index.adoc[Local meetups]. Jenkins contributors organize many local CI/CD and Jenkins meetups around the world. There might be one in your city!
* xref:contributor-summit:index.adoc[Contributor Summits]. We organize a few contributor summits every year. It brings together current community members and future contributors to learn, meet, and help shape the future of Jenkins.
* xref:devops-world:index.adoc[DevOps World]. CloudBees organizes the DevOps World conference and includes Jenkins topics in the conference agenda.
* xref:hacktoberfest:index.adoc[Hacktoberfest]. Jenkins project is participating to Hacktoberfest.

== Major Events

++++
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/haml-js/0.4.0/haml.min.js"></script>-->

<!--<script type="text/javascript">-->
<!--  const hamlCode = `.row-->

<!-- - # Sort by the date defined for each of the events-->
<!-- - now = Time.now.utc-->

<!-- - no_events = true-->

<!-- - site.events.keys.each do |name|-->
<!-- - data = site.events[name]-->

<!-- - raise ArgumentError.new("No 'date' specified: #{name}")  unless data.date-->
<!-- - raise ArgumentError.new("No 'title' specified: #{name}") unless data.title-->
<!-- - raise ArgumentError.new("No 'link' specified: #{name}") unless data.link-->
<!-- - data.event_time = Time.parse(data.date)-->

<!-- - site.events.keys.sort { |x,y| site.events[x].event_time <=> site.events[y].event_time }.each do |name|-->
<!-- - data = site.events[name]-->

<!-- - event_time = data.event_time-->

<!-- - next unless event_time > now-->
<!-- - no_events = false-->

<!-- - raise ArgumentError.new("No 'location' specified: #{name}") unless data.location-->

<!--.col-md-3.text-center-->
<!--  %ul.ji-item-list-->
<!--    %li.post.event.floating-->
<!--      %a.body{href: data.link, target: '_blank', rel: 'noreferrer noopener'}-->
<!--        .header.time-->
<!--          .date-time-->
<!--            .date-->
<!--              .month-->
<!--                = event_time.strftime('%b')-->

<!--              .day-->
<!--                = event_time.strftime('%-d')-->

<!--              .dow-->
<!--                = event_time.strftime('%a')-->

<!--            .time-->
<!--              = event_time.strftime('%l:%M %P')-->

<!--        %h5.title-->
<!--          = data.title-->

<!--        = data.location-->

<!--      %p.teaser.collapsed{onclick: "this.classList.toggle('collapsed')"}-->
<!--        = data.raw_content-->

<!--        .more-->
<!--      .attrs-->
<!-- - if no_events-->
<!--%p-->
<!--  There are no upcoming major events registered in the database.-->
<!--  If you see that your event is missing, please submit a change to our website.-->
<!--%p-->
<!--  %a.body{href: 'https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-an-event', target: '_blank', rel: 'noreferrer noopener'}-->
<!--    | How to add an event to the Jenkins website?`;-->
<!--   const htmlCode = Haml.render(hamlCode);-->

<!-- document.body.innerHTML = htmlCode;-->

<!--</script>-->

<style>
.ji-dated-list,
.ji-item-list,
.ji-item-list>post,
.ji-item-list>post>.body,
.ji-item-list>.post>.body {
  display: block;
  position: relative;
  padding: 0;
  margin: 0;
  list-style: none;
  font-size:1rem;
}
.events .ji-item-list{
  text-align: center;
  white-space: nowrap;
  overflow: visible;
  overflow-x: auto;
  border-bottom:1px solid #ccc;
  vertical-align:top;
}

.events .ji-item-list>.event{
  display:inline-block;
  margin:0;
  vertical-align:top;
}
.events .ji-item-list>.event>a{
  width:16rem;
  padding:.75rem;
  margin:1rem .25rem .25rem;
  white-space:normal;
  text-decoration:none;
}
.events .ji-item-list>.event>a .title{
  margin:.75rem 0 .25rem;
  height:1.1rem;
  overflow:hidden;
  position:relative;
}
.events .ji-item-list>.event>a .title:after{
  content:' ';
  display:block;
  position:absolute;
  height:1.1rem;
  width:10%;
  box-shadow:inset white -3rem 0 2rem -2rem;
  bottom:0; right:0;
}
.events .ji-item-list>.event>a .teaser{
  color:#4a5568;
  font-size:.85rem;
  height:3.3rem;
  overflow:hidden;
  position:relative;
}
.events .ji-item-list>.event>a .teaser:after{
  content:' ';
  display:block;
  position:absolute;
  height:1.1rem;
  width:25%;
  box-shadow:inset white -6rem 0 3rem -3rem;
  bottom:0; right:0;
}
</style>

<div class="col-md-3 text-center">
    <ul class="ji-item-list">
        <li class="post event floating">
        <a class="body" href="https://www.devopsworldjenkins.com/" target="_blank" rel="noreferrer noopener">
            <div class="header time">
            <div class="date-time">
                <div class="date">
                <div class="month">Sep</div>
                <div class="day">28</div>
                <div class="dow">Tue</div>
                </div>
                <div class="time">9:00 AM</div>
            </div>
            </div>
            <h5 class="title">DevOps World | Jenkins World 2021</h5>
            Online
        </a>
        <p class="teaser collapsed" onclick="this.classList.toggle('collapsed')">
            DevOps World | Jenkins World is the largest gathering of Jenkins users in the world, including Jenkins experts, continuous delivery thought leaders and companies offering complementary technologies for Jenkins. Join us online September 28-30, 2021.
            <div class="more"></div>
        </p>
        <div class="attrs">
            <span class="location">Online</span>
        </div>
        </li>
    </ul>
</div>
<div>
    <p>
        There are no upcoming major events registered in the database.
        If you see that your event is missing, please submit a change to our website.
    </p>
    <p>
        <a href="https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-an-event" target="_blank" rel="noreferrer noopener">How to add an event to the Jenkins website?</a>
    </p>
</div>
++++

[#event-calendar]
== Event Calendar

We have a calendar which lists events related to Jenkins, including regular SIG and project meetings. This calendar is also available in the https://calendar.google.com/calendar/ical/4ss12f0mqr3tbp1t2fe369slf4%40group.calendar.google.com/public/basic.ics[(.ics format)]

++++
<!-- Using JSTZ time zone detection library -->
<script src="
https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script type="text/javascript">
  const deviceTimeZone = jstz.determine().name();

  const calendarSrc = 'https://calendar.google.com/calendar/b/1/embed'

      + '?showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;mode=WEEK'
      + '&amp;src=4ss12f0mqr3tbp1t2fe369slf4%40group.calendar.google.com&amp;color=%2329527A'
      + '&amp;ctz='
  const calendarSrcPrefix = '<iframe src="' + calendarSrc;

  const calendarSrcSuffix = '" style="border:0;overflow:hidden;" width="1024" height="600" scrolling="no"></iframe>';

  function set_calendar(timezone) {
    timezone = timezone || deviceTimeZone;

    document.getElementById('calendar-container').innerHTML = calendarSrcPrefix + encodeURIComponent(timezone) + calendarSrcSuffix;

  }

  $(function () {
    set_calendar(deviceTimeZone);
  });
</script>


<div class="row">
    <div class="col">
        <!-- The following div's innerHTML will be overwritten with the-->
        <!-- calendar iframe set to the appropriate time zone. -->
        <div id="calendar-container"></div>
        <p>
            View calendar using TimeZone:
            <select id="selected_timezone" onchange="set_calendar(this.value)">
                <option value="">(auto)</option>
                <option value="GMT">GMT</option>
                <option value="CET">CET</option>
                <option value="America/New_York">US Eastern</option>
                <option value="America/Los_Angeles">US Pacific</option>
                <option value="Asia/Tokyo">Tokyo</option>
                <option value="Asia/Shanghai">Shanghai</option>
            </select>
        </p>
    </div>
</div>
++++
