= Security Advisories

This page lists all security advisories that have been published so far.

This index is also available as an RSS feed.

++++
<!--<script type="text/javascript">-->
<!--    function getFiles(dir, files = []) {-->
<!--        const directory = dir;-->
<!--        const xmlHttp = new XMLHttpRequest();-->
<!--        xmlHttp.open('GET', directory, false); // false for synchronous request-->
<!--        xmlHttp.send(null);-->
<!--        const ret = xmlHttp.responseText;-->
<!--        const fileList = ret.split('\n');-->
<!--        // for (let i = 0; i < fileList.length; i++) {-->
<!--        //     const fileinfo = fileList[i].split(' ');-->
<!--        //     if (fileinfo[0] == '201:') {-->
<!--        //         document.write(fileinfo[1] + "<br>");-->
<!--        //         document.write('<img src=\"' + directory + fileinfo[1] + '\"/>');-->
<!--        //     }-->
<!--        // }-->

<!--        return fileList;-->
<!--    }-->

<!--    const filesInTheFolder = getFiles('..');-->
<!--    console.log("filesInTheFolder", filesInTheFolder);-->
<!--</script>-->

<script src="
https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<script type="text/javascript">
    function getFiles(dir, files = []) {
        let fileNames = new Array();
        $.ajax({
            url: "/security/advisories",
            success: function(data){
                $(data).find("").each(function(){
                    if(openFile($(this).attr("href"))){
                        fileNames.push($(this).attr("href"));
                    }
                });
            }
        });

        return fileNames;
    }

    const filesInTheFolder = getFiles('.');
    console.log("filesInTheFolder", filesInTheFolder);
</script>

<!--advisories_dir = File.expand_path(File.dirname(__FILE__) + '/advisory')-->
<!--pages_by_path = site.pages.map { |p| [p.source_path, p] }.to_h-->
<!--adocs = Dir.glob(File.join(advisories_dir, '*.{ad,adoc}'))-->
<!--years = adocs.select { |it| it =~ /(20\d\d)/ }.map { |it| /(20\d\d)/.match(it)[1] }.uniq.sort-->
++++

// :ruby
// require 'asciidoctor'
// advisories_dir = File.expand_path(File.dirname(__FILE__) + '/advisory')
//
//   pages_by_path = site.pages.map { |p| [p.source_path, p] }.to_h
//
//   adocs = Dir.glob(File.join(advisories_dir, '*.{ad,adoc}'))
//
//   years = adocs.select { |it| it =~ /(20\d\d)/ }.map { |it| /(20\d\d)/.match(it)[1] }.uniq.sort
//
// .container
//   .row
//     %p
//       This page lists all security advisories that have been published so far.
//   .row
//     %p
//       This index is also available as an
//       %a{:href => '/security/advisories/rss.xml'}
//         RSS feed.
//
// - years.reverse_each do |year|
// .row
// .container
// .row
// %h3
// = year
//
//         .row
//           %ul
//             - advisories = Dir.glob(File.join(advisories_dir, year + '-*.{ad,adoc}'))
//
// - advisories.sort.reverse_each do |advisory|
// - page = pages_by_path[advisory]
//
//               %li
//                 %a{:href => expand_link(page.url)}
//                   = page.title
//
// - if year.to_i < 2018
// = "(#{page.kind})"
//
// - if page.issues and year.to_i >= 2018 or page.index_details
//
//                   %br
//                   %small
//                     - if page.index_details
//                       = Asciidoctor.convert page.index_details, safe: :safe
//
// - else
// %ul
// - if page.core
// %li
// Affects Jenkins Core
// - plugins = get_plugins(page.issues).uniq.sort { |x,y| (site._generated[:update_center].plugins[x.name]&.title&.downcase || x.name&.downcase) <=> (site._generated[:update_center].plugins[y.name]&.title&.downcase || y.name&.downcase) }
//
// - if plugins.size > 0
// %li
// %span{:style => 'white-space: nowrap;'}
// Affects Plugins:
// - plugins.each_with_index do | plugin, idx |
// - if site._generated[:update_center].plugins[plugin.name]
// %a{:href => 'https://plugins.jenkins.io/' + plugin.name, :style => 'white-space: nowrap; padding: 2px;'}
// = site._generated[:update_center].plugins[plugin.name].title
//
// - else
// = plugin.title || plugin.name
//
// - components = page.issues.collect { |issue| issue.components }.flatten.keep_if { |c| c }
//
// - if components.size > 0
// - components.each do | component |
// %li
// %span{:style => 'white-space: nowrap;'}
// Affects
// = component.title || component.name