= Source Code Hosting

The Jenkins project only publishes free and open source plugins distributed under an link:https://opensource.org/licenses/[OSI-approved] license.

The canonical source code repository is in the `jenkinsci` GitHub organization to ensure source code access and project continuity in case previous maintainers move on.
Some plugins we distribute are currently maintained outside the `jenkinsci` GitHub organization for historical reasons, but this is discouraged.
link:forks[This page] lists all forked repositories in the `jenkinsci` GitHub organization and their source repositories.

Plugin maintainers typically have repository admin permissions for plugins they maintain, but some features (like transfer and deletion of repos) are disabled.

This table shows the permissions currently granted to contributors in the `jenkinsci` GitHub repositories, excluding organization owners with full permissions to every repository:

////
Testing changes to the script below locally without major changes is difficult due to CORS set up on reports.jenkins.io to only allow access from jenkins.io.
Starting Chrome with the arguments --disable-web-security --user-data-dir=<some dir> seems to be the easiest option.
////
++++
<table id="permissions" className="display" style="width:100%">
  <thead>
  <tr>
    <th>Repository</th>
    <th>User</th>
    <th>Access</th>
  </tr>
  </thead>
  <tfoot>
  <tr>
    <th>Repository</th>
    <th>User</th>
    <th>Access</th>
  </tr>
  </tfoot>
</table>
++++
