= Participate and Contribute

There are many ways to engage with the Jenkins project and community. Here are the most common ways to get you started. Welcome aboard!

[.participate]
.CONNECT
****
Join our communication channels, discuss and help us spread the word!

xref:connect.adoc[Read More]
****

.MEET
****
Meet other Jenkins users and share your experiences by organizing and attending events and meetups.

xref:meet.adoc[Read More]
****

.CODE
****
Do you enjoy writing code? There are numerous plugins and components for you to contribute to.

xref:code.adoc[Read More]
****

.HELP
****
As an experienced user, you can help others get the most out of Jenkins.

xref:help.adoc[Read More]
****

.TRANSLATE
****
If you're fluent in languages other than English, consider improving support for those languages.

xref:dev-docs:internationalization:index.adoc[Read More]
****

.TEST
****
You can help prevent regressions by contributing automated tests.

xref:test.adoc[Read More]
****

.DOCUMENT
****
Improve the documentation to make it easier for others to get started.

xref:document.adoc[Read More]
****

.DESIGN
****
As it is intended for daily use by finicky web developers, design is essential.

xref:design.adoc[Read More]
****

.REVIEW
****
Help review changes to code or documentation.

xref:review-changes.adoc[Read More]
****

.DONATE
****
If you have no time but want to help, we accept money to facilitate project goals.

xref:meet.adoc[Read More]
****