= Artifact Promotion plugin for Jenkins Pipeline

*Project goal:* Create a new highly anticipated engine for managing promotions in Jenkins Pipeline, with modern UIs and REST APIs

*Skills to study/improve:* Java, JavaScript, REST API

This project idea is published as a Google doc. You are welcome to comment on the proposal or to suggest changes in the draft embedded below ( Google Doc )

++++
<iframe src="https://docs.google.com/document/d/1UYi0jIYsKHE5IGS84B5W0XBoeMyF4yY_exu-21O99U8" width="100%" height="600px"></iframe>
++++


== Potential Mentors
[.avatar]
*Student*: 
image:images:ROOT:avatars/[,width=30,height=30] 

[.avatar]
*Mentor(s):*
image:images:ROOT:avatars/[,width=30,height=30] 
image:images:ROOT:avatars/[,width=30,height=30] 
image:images:ROOT:avatars/[,width=30,height=30] 
image:images:ROOT:avatars/[,width=30,height=30] 
image:images:ROOT:avatars/[,width=30,height=30] 


See https://docs.google.com/document/d/1UYi0jIYsKHE5IGS84B5W0XBoeMyF4yY_exu-21O99U8[Google Doc]

== Organization Links 
* xref:gsoc:index.adoc[Jenkins GSoC page] - documentation, application guidelines
* xref:community:ROOT:index.adoc[Participate and contribute to Jenkins] - landing page for newcomer contributors
* https://issues.jenkins.io/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20labels%20%3D%20newbie-friendly%20[Newbie-friendly issues] - list of organization-wide newbie-friendly issues (use them if there is no links in the project idea)
> xref:2019/project-ideas[Go back to other GSoC 2021 project ideas]